
$background = rgba(3c474dff)
$primary = rgba(d9bb80ff)
$on_primary = rgba(dbbc7fff)



#not in use
$error = rgba(ff7a6dff)
$error_container = rgba(7b0007ff)
$inverse_on_surface = rgba(424951ff)
$inverse_primary = rgba(007073ff)
$inverse_surface = rgba(dce3eeff)
$on_background = rgba(5c636cff)
$on_error = rgba(390001ff)
$on_error_container = rgba(ffbbb3ff)
$on_primary_container = rgba(53dfe3ff)
$on_primary_fixed = rgba(bbfdffff)
$on_primary_fixed_variant = rgba(48d7dbff)
$on_secondary = rgba(001b1cff)
$on_secondary_container = rgba(85dadcff)
$on_secondary_fixed = rgba(bbfdffff)
$on_secondary_fixed_variant = rgba(7dd2d4ff)
$on_surface = rgba(c4cbd6ff)
$on_surface_variant = rgba(96a4b6ff)
$on_tertiary = rgba(00192dff)
$on_tertiary_container = rgba(a3d0ffff)
$on_tertiary_fixed = rgba(e9f2ffff)
$on_tertiary_fixed_variant = rgba(99c8f8ff)
$outline = rgba(768495ff)
$outline_variant = rgba(2d3b4aff)
$primary_container = rgba(004143ff)
$primary_fixed = rgba(005b5dff)
$primary_fixed_dim = rgba(004143ff)
$scrim = rgba(000000ff)
$secondary = rgba(5bb0b2ff)
$secondary_container = rgba(004143ff)
$secondary_fixed = rgba(005b5dff)
$secondary_fixed_dim = rgba(004143ff)
$shadow = rgba(000000ff)
$source_color = rgba(267ebfff)
$surface = rgba(0d141bff)
$surface_bright = rgba(333a42ff)
$surface_container = rgba(192028ff)
$surface_container_high = rgba(242b33ff)
$surface_container_highest = rgba(2e353eff)
$surface_container_low = rgba(151c24ff)
$surface_container_lowest = rgba(080f16ff)
$surface_dim = rgba(0d141bff)
$surface_tint = rgba(4cdadeff)
$surface_variant = rgba(3a4857ff)
$tertiary = rgba(78a7d5ff)
$tertiary_container = rgba(003d63ff)
$tertiary_fixed = rgba(20547eff)
$tertiary_fixed_dim = rgba(003d63ff)

