
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = swww-daemon
exec-once = hyprlock
exec-once = waybar
exec-once = fcitx5 -d



env = GTK_THEME,adw-gtk3-dark
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec-once = xsettingsd &

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons   
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx

