-- Generated by hellwal.
--
-- This is a Neovim colorscheme based on your wallpaper's color palette.
-- To use, add 'vim.cmd("colorscheme hellwal")' to your Neovim config.

local colors = {
	background = "#%% background.hex %%",
	foreground = "#%% foreground.hex %%",
	cursor = "#%% cursor.hex %%",
	border = "#%% border.hex %%",

	color0 = "#%% color0.hex %%",
	color1 = "#%% color1.hex %%",
	color2 = "#%% color2.hex %%",
	color3 = "#%% color3.hex %%",
	color4 = "#%% color4.hex %%",
	color5 = "#%% color5.hex %%",
	color6 = "#%% color6.hex %%",
	color7 = "#%% color7.hex %%",
	color8 = "#%% color8.hex %%",
	color9 = "#%% color9.hex %%",
	color10 = "#%% color10.hex %%",
	color11 = "#%% color11.hex %%",
	color12 = "#%% color12.hex %%",
	color13 = "#%% color13.hex %%",
	color14 = "#%% color14.hex %%",
	color15 = "#%% color15.hex %%",
}

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.o.background = "dark"

-- Normal background and foreground
vim.api.nvim_set_hl(0, "Normal", { bg = colors.background, fg = colors.foreground })

-- General UI elements
vim.api.nvim_set_hl(0, "Comment", { fg = colors.color3, italic = true })
vim.api.nvim_set_hl(0, "CursorLine", { bg = colors.color0 })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = colors.cursor, bg = colors.color0 })
vim.api.nvim_set_hl(0, "SignColumn", { bg = colors.background })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = colors.color0 })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.color8, bg = colors.background })
vim.api.nvim_set_hl(0, "NonText", { fg = colors.color1, bg = colors.background })
vim.api.nvim_set_hl(0, "Visual", { bg = colors.color1 })
vim.api.nvim_set_hl(0, "Search", { fg = colors.color0, bg = colors.color10 })

-- Code syntax
vim.api.nvim_set_hl(0, "String", { fg = colors.color2 })
vim.api.nvim_set_hl(0, "Number", { fg = colors.color6 })
vim.api.nvim_set_hl(0, "Boolean", { fg = colors.color4 })
vim.api.nvim_set_hl(0, "Function", { fg = colors.color14 })
vim.api.nvim_set_hl(0, "Statement", { fg = colors.color5 })
vim.api.nvim_set_hl(0, "Keyword", { fg = colors.color5 })
vim.api.nvim_set_hl(0, "Type", { fg = colors.color4 })
vim.api.nvim_set_hl(0, "Identifier", { fg = colors.color12 })

-- Terminal colors
vim.g.terminal_color_0 = colors.color0
vim.g.terminal_color_1 = colors.color1
vim.g.terminal_color_2 = colors.color2
vim.g.terminal_color_3 = colors.color3
vim.g.terminal_color_4 = colors.color4
vim.g.terminal_color_5 = colors.color5
vim.g.terminal_color_6 = colors.color6
vim.g.terminal_color_7 = colors.color7
vim.g.terminal_color_8 = colors.color8
vim.g.terminal_color_9 = colors.color9
vim.g.terminal_color_10 = colors.color10
vim.g.terminal_color_11 = colors.color11
vim.g.terminal_color_12 = colors.color12
vim.g.terminal_color_13 = colors.color13
vim.g.terminal_color_14 = colors.color14
vim.g.terminal_color_15 = colors.color15

-- Final command to load the colorscheme
vim.cmd([[colorscheme hellwal]])
