-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#191113",
	base01 = "#140c0e",
	base02 = "#22191b",
	base03 = "#514346",
	base04 = "#d6c2c5",
	base05 = "#efdee0",
	base06 = "#382e30",
	base07 = "#413738",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ffb4ab",
	base09 = "#edbe92",
	base0A = "#e4bdc4",
	base0B = "#ffb1c3",
	base0C = "#ffdcbe",
	base0D = "#ffb1c3",
	base0E = "#ffd9e0",
	base0F = "#8d4a5b",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#713344",
	fg = "#191113",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#60401e",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#e65181",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#e65181",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#8d4a5b",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#140c0e",
	fg = "#ffb1c3",
})
