-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#0d141b",
	base01 = "#080f16",
	base02 = "#151c24",
	base03 = "#2d3b4a",
	base04 = "#96a4b6",
	base05 = "#c4cbd6",
	base06 = "#424951",
	base07 = "#333a42",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ff7a6d",
	base09 = "#78a7d5",
	base0A = "#5bb0b2",
	base0B = "#00b5b9",
	base0C = "#a3d0ff",
	base0D = "#4cdade",
	base0E = "#53dfe3",
	base0F = "#007073",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#004143",
	fg = "#0d141b",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#003d63",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#267ebf",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#267ebf",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#007073",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#080f16",
	fg = "#00b5b9",
})
