-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#0f1417",
	base01 = "#0a0f12",
	base02 = "#171c1f",
	base03 = "#40484d",
	base04 = "#c0c7cd",
	base05 = "#dfe3e7",
	base06 = "#2c3134",
	base07 = "#353a3d",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ffb4ab",
	base09 = "#c9c1ea",
	base0A = "#b5c9d7",
	base0B = "#8ecff2",
	base0C = "#e5deff",
	base0D = "#8ecff2",
	base0E = "#c2e8ff",
	base0F = "#196585",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#004d67",
	fg = "#0f1417",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#484364",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#487a94",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#487a94",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#196585",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#0a0f12",
	fg = "#8ecff2",
})
